const seen = require("/root/.openclaw/workspace/memory/velo-news-seen.json");

const scraped = [
  {"title": "OpenAI, In Collaboration With Crypto Firm Paradigm, Unveil EVMBench - A Tool To Evaluate Agent Performance With Smart Contracts", "date": "2/19/2026"},
  {"title": "Coinbase's Base Network Moves Away From Optimism Stack To Create Their Own", "date": "2/19/2026"},
  {"title": "Lighter Reaches Over 50% Of Circulating Tokens Staked After Platform Rolls Out Staking Utility", "date": "2/19/2026"},
  {"title": "Hyperliquid Launches Lobbying Group \"Hyperliquid Policy Center\" Led By Jake Chervinsky, Hyperliquid Foundation To Seed It With $28M Of $HYPE", "date": "2/18/2026"},
  {"title": "BlackRock To Keep 18% Of Staking Fees Generated By New Staked Ethereum ETF", "date": "2/18/2026"},
  {"title": "Crypto VC Dragonfly Raises $650M For Fourth Fund", "date": "2/17/2026"},
  {"title": "CRYPTO LENDING COMPANY FIGURE DISCLOSES DATA BREACH, DATA INCLUDES NAMES, ADDRESSES, DATE OF BIRTH, AND PHONE NUMBERS", "date": "2/14/2026"},
  {"title": "BINANCE FIRED COMPLIANCE TEAM MEMBERS WHO UNCOVERED IRAN SANCTION VIOLATIONS IN LATE 2025", "date": "2/14/2026"},
  {"title": "TOMASZ STANCZAK TO STEP DOWN AS ETHEREUM FOUNDATION CO-EXECUTIVE DIRECTOR", "date": "2/13/2026"},
  {"title": "Binance France CEO Targeted In Home Invasion Attempt, As Crypto Crime Cases In France Grow", "date": "2/13/2026"},
  {"title": "MARC ZELLER, FOUNDER OF ACI, COMMENTS ON AAVE LABS RECENT PROPOSAL, SAYING IT IS \"TEXTBOOK EXTRACTION\" TO ASK FOR A \"QUARTER OF ALL TREASURY MONEY AND A THIRD OF $AAVE RESERVES\"", "date": "2/13/2026"},
  {"title": "Polymarket Expands Crypto Price Markets, Allowing Users To Bet Whether Coins Will Trade Up Or Down In The Next 5 Minutes", "date": "2/13/2026"},
  {"title": "Lighter Strikes Deal With Circle To Share Revenue Generated On The $920M Of USDC Deposited On The Platform", "date": "2/12/2026"},
  {"title": "Hyperliquid Strategies (PURR) Announces Earnings, Purchased 5 Million $HYPE Tokens Using $129.5M At A Price Of $25.9, With $125M In Cash Remaining", "date": "2/11/2026"},
  {"title": "Goldman Sachs Discloses $1.1B In BTC, $1B In ETH, $153M In XRP And $108M In SOL - Representing A 0.33% Crypto Allocation", "date": "2/11/2026"},
  {"title": "SAM BANKMAN-FRIED SEEKS A RETRIAL FOR FTX CASE IN NEW YORK", "date": "2/11/2026"},
  {"title": "Polymarket To Venture Into Attention Markets, Allowing Users To Bet On Trends And Public Opinion", "date": "2/10/2026"},
  {"title": "Backpack Exchange Looking To Raise $50M At A $1B Valuation Whilst Claiming To Have Made Over $100M In 2025 - Polymarket Odds Give A 29% Chance Of It Sustaining A $1B Valuation After TGE", "date": "2/10/2026"},
  {"title": "SOUTH KOREA BEGINS INVESTIGATIONS INTO BITHUMB AFTER 620,000 BTC AIRDROP ERROR, CITING EXPOSED \"STRUCTURAL VULNERABILITIES\"", "date": "2/10/2026"},
  {"title": "Jump Trading To Acquire A Stake In Polymarket In Exchange For Providing Liquidity", "date": "2/10/2026"}
];

const seenTitles = new Set(seen.seenArticles.map(a => a.title.toLowerCase().trim()));
const newArticles = scraped.filter(a => !seenTitles.has(a.title.toLowerCase().trim()));

console.log(JSON.stringify({
  newCount: newArticles.length,
  newArticles: newArticles
}, null, 2));
